wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728425766.398721
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      - 105
      2:
      - 1
      - 3
      - 9
      - 55
      - 103
      - 105
      3:
      - 23
      4: 3.9.19
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
